#!/usr/bin/env node

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_URL = "https://www.dallascowboys.com/team/players-roster/";
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(scriptDirectory, "../data/roster.js");

const stars = new Set([
  "Brandon Aubrey",
  "DaRon Bland",
  "Caleb Downs",
  "Jake Ferguson",
  "Rashan Gary",
  "CeeDee Lamb",
  "DeMarvion Overshown",
  "George Pickens",
  "Dak Prescott",
  "Tyler Smith",
  "Javonte Williams",
  "Quinnen Williams",
]);

const core = new Set([
  ...stars,
  "Bryan Anger",
  "Cooper Beebe",
  "Jaydon Blue",
  "Tyler Booker",
  "Kenny Clark",
  "Donovan Ezeiruaku",
  "Tyler Guyton",
  "Malik Hooker",
  "Marist Liufau",
  "P.J. Locke",
  "Shavon Revel Jr.",
  "Trent Sieg",
  "Terence Steele",
  "KaVontae Turpin",
]);

function decodeHtml(value) {
  return value
    .replace(/<[^>]*>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&quot;/g, '"')
    .replace(/&#x27;|&#39;/g, "'")
    .replace(/&nbsp;/g, " ")
    .replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code)))
    .replace(/\s+/g, " ")
    .trim();
}

function getMatch(value, pattern, label) {
  const match = value.match(pattern);
  if (!match) throw new Error(`Could not find ${label} in a roster row.`);
  return decodeHtml(match[1]);
}

function parseRoster(html) {
  const reserveMarker = html.indexOf("Reserve/Injured");
  const rows = [...html.matchAll(/<tr><td class="sorter-lastname"[\s\S]*?<\/tr>/g)];

  return rows.map((rowMatch) => {
    const row = rowMatch[0];
    const cells = [...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/g)].map((match) =>
      decodeHtml(match[1]),
    );
    const name = getMatch(row, /title="([^"]+)"/, "player name");
    const image = getMatch(
      row,
      /<img alt="" class="img-responsive" src="([^"]+)"/,
      "headshot",
    ).replace(
      /\/t_thumb_squared\/t_lazy\/f_(?:auto|png)\//,
      "/w_600,h_600,c_fill,g_face,q_auto:good/f_auto/",
    );

    if (image.includes("/t_lazy/")) {
      throw new Error(`Could not convert the lazy headshot for ${name}.`);
    }
    const profilePath = getMatch(
      row,
      /<a href="([^"]+)" title="[^"]+">/,
      "profile link",
    );

    if (cells.length < 8) {
      throw new Error(`Expected eight columns for ${name}; found ${cells.length}.`);
    }

    return {
      id: profilePath.split("/").filter(Boolean).at(-1),
      name,
      number: cells[1],
      position: cells[2],
      height: cells[3],
      weight: Number(cells[4]),
      age: Number(cells[5]),
      experience: cells[6],
      college: cells[7],
      image,
      profile: new URL(profilePath, SOURCE_URL).href,
      status: reserveMarker !== -1 && rowMatch.index > reserveMarker ? "Reserve/Injured" : "Active",
      tier: stars.has(name) ? "star" : core.has(name) ? "core" : "roster",
    };
  });
}

async function main() {
  const response = await fetch(SOURCE_URL, {
    headers: { "user-agent": "Cowboys Roster Trainer updater (personal study project)" },
  });
  if (!response.ok) throw new Error(`Roster request failed with HTTP ${response.status}.`);

  const players = parseRoster(await response.text());
  if (players.length < 50) {
    throw new Error(`Only found ${players.length} players; the official markup may have changed.`);
  }

  const payload = {
    meta: {
      source: SOURCE_URL,
      updated: new Date().toISOString().slice(0, 10),
      season: new Date().getFullYear(),
    },
    players,
  };

  const output = `// Generated by scripts/update-roster.mjs.\nwindow.COWBOYS_ROSTER = ${JSON.stringify(payload, null, 2)};\n`;
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
  console.log(`Wrote ${players.length} players to ${outputPath}`);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
